apiVersion: v1
kind: Namespace
metadata:
  name: config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: config
data:
  config: '{ "setting1": "value1", "setting2": "value2" }'
  path: /opt/app
