apiVersion: v1
kind: Namespace
metadata:
  name: affinity
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web-server
  name: the-app-pod
  namespace: affinity
spec:
  containers:
  - image: nginx:1.29.0
    name: the-app-pod
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: tier
            operator: In
            values:
            - frontend
