apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-set
  namespace: database
spec:
  serviceName: "db-headless"
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
