apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-logger
  namespace: security
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
      - name: logger
        image: alpine:3.20
        command: ["nc", "-lk", "-p", "7000"]
        ports:
        - containerPort: 7000
