apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session
  template:
    metadata:
      labels:
        app: session
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
