apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: ckad
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        event-ttl: "8h0m0s"
  extraMounts:
  - hostPath: /workspaces/ckad/.cluster/mounts/data
    containerPath: /mnt/data
  - hostPath: /workspaces/ckad/.cluster/mounts/projects
    containerPath: /mnt/projects
  - hostPath: /workspaces/ckad/.cluster/mounts/storage
    containerPath: /tmp/storage
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
    listenAddress: "127.0.0.1"
  - containerPort: 443
    hostPort: 443
    protocol: TCP
    listenAddress: "127.0.0.1"
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "127.0.0.1"
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "127.0.0.1"
  - containerPort: 30443
    hostPort: 30443
    listenAddress: "127.0.0.1"
- role: worker
  extraMounts:
  - hostPath: /workspaces/ckad/.cluster/mounts/data
    containerPath: /mnt/data
  - hostPath: /workspaces/ckad/.cluster/mounts/projects
    containerPath: /mnt/projects
  - hostPath: /workspaces/ckad/.cluster/mounts/storage
    containerPath: /tmp/storage
  - hostPath: /workspaces/ckad/.cluster/mounts/frontend
    containerPath: /tmp/frontend
  extraPortMappings:
  - containerPort: 30000
    hostPort: 40000
    listenAddress: "127.0.0.1"
  - containerPort: 30080
    hostPort: 40080
    listenAddress: "127.0.0.1"
  - containerPort: 30443
    hostPort: 40443
    listenAddress: "127.0.0.1"
  labels:
    tier: frontend
- role: worker
  extraMounts:
  - hostPath: /workspaces/ckad/.cluster/mounts/data
    containerPath: /mnt/data
  - hostPath: /workspaces/ckad/.cluster/mounts/projects
    containerPath: /mnt/projects
  - hostPath: /workspaces/ckad/.cluster/mounts/storage
    containerPath: /tmp/storage
  - hostPath: /workspaces/ckad/.cluster/mounts/backend
    containerPath: /tmp/backend
  extraPortMappings:
  - containerPort: 30000
    hostPort: 50000
    listenAddress: "127.0.0.1"
  - containerPort: 30080
    hostPort: 50080
    listenAddress: "127.0.0.1"
  - containerPort: 30443
    hostPort: 50443
    listenAddress: "127.0.0.1"
  labels:
    tier: backend


