apiVersion: v1
kind: Namespace
metadata:
  name: netpol-demo4
---
apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: netpol-demo4
  labels:
    app: web
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: netpol-demo4
  labels:
    access: web
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sleep", "3600"]
