apiVersion: v1
kind: Namespace
metadata:
  name: netpol-demo5
---
apiVersion: v1
kind: Pod
metadata:
  name: egress-pod
  namespace: netpol-demo5
spec:
  containers:
  - name: alpine
    image: alpine:3.20
    command: ["sleep", "3600"]
