apiVersion: v1
kind: Namespace
metadata:
  name: netpol-demo10
---
apiVersion: v1
kind: Pod
metadata:
  name: locked-down
  namespace: netpol-demo10
spec:
  containers:
  - name: alpine
    image: alpine:3.20
    command: ["sleep", "3600"]
