apiVersion: v1
kind: Namespace
metadata:
  name: netpol-demo1
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: netpol-demo1
  labels:
    app: backend
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: netpol-demo1
  labels:
    role: frontend
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sleep", "28800"]
