apiVersion: v1
kind: Namespace
metadata:
  name: netpol-demo8
---
apiVersion: v1
kind: Pod
metadata:
  name: multi-port-pod
  namespace: netpol-demo8
  labels:
    app: multi-port
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
    - name: https
      containerPort: 443
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: netpol-demo8
  labels:
    role: frontend
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: admin
  namespace: netpol-demo8
  labels:
    role: admin
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sleep", "3600"]
