apiVersion: v1
kind: Namespace
metadata:
  name: affinity
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    service: cache-server
  name: cache-server
  namespace: affinity
spec:
  containers:
  - image: redis:7.2
    name: cache
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: tier
            operator: In
            values:
            - backend
