apiVersion: v1
kind: Namespace
metadata:
  name: task10
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: help-me
  name: help-me
  namespace: task10
spec:
  containers:
  - image: nginx:latset
    name: help-me
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
