apiVersion: v1
kind: Namespace
metadata:
  name: limits
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: max-pods
  namespace: limits
spec:
  hard:
    pods: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit
  namespace: limits
spec:
  limits:
  - type: Container
    max:
      cpu: 200m
      memory: 256Mi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 120m
      memory: 128Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
