apiVersion: v1
kind: Namespace
metadata:
  name: task2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-deploy
  name: api-deploy
  namespace: task2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-deploy
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-deploy
    spec:
      containers:
      - image: nginx:1.25
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
