apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache-deploy
  name: cache-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache-deploy
  template:
    metadata:
      labels:
        app: cache-deploy
    spec:
      containers:
      - image: redis:8.0.2
        name: redis
