apiVersion: v1
kind: Namespace
metadata:
  name: canary-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo-stable
  namespace: canary-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-demo
      track: stable
  template:
    metadata:
      labels:
        app: canary-demo
        track: stable
    spec:
      containers:
      - name: app
        image: nginx:1.21
---
apiVersion: v1
kind: Service
metadata:
  name: canary-demo-svc
  namespace: canary-demo
spec:
  selector:
    app: canary-demo
    track: stable
  ports:
  - port: 80
    targetPort: 80
