apiVersion: v1
kind: Namespace
metadata:
  name: blue-green
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-demo-blue
  namespace: blue-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-demo
      version: blue
  template:
    metadata:
      labels:
        app: blue-green-demo
        version: blue
    spec:
      containers:
      - name: app
        image: nginx:1.25
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-demo-svc
  namespace: blue-green
spec:
  selector:
    app: blue-green-demo
    version: blue
  ports:
  - port: 80
    targetPort: 80
